### ISSUE TITLE
Tests coverage is missing e2e tests

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/twake-drive-legacy#27]
We don't have the e2e tests coverage data, services/documents isn't here:

![Screenshot 2023-04-19 at 10 13 09](https://user-images.githubusercontent.com/14353924/233011954-02f6fde4-5267-4267-ad45-5c4e533c99b7.png)

**Comment by RomaricMourgues** [comment]
While investigating I confirm the tdrive/coverage/merged/coverage-report.txt doesn't match what is shown in the PR comment. @MontaGhanmy any idea ?

![Screenshot 2023-04-19 at 11 11 46](https://user-images.githubusercontent.com/14353924/233027584-a41ada25-2007-4c71-9339-dcff7e3b4be0.png)

**Comment by RomaricMourgues** [comment]
So after trying a lot o other actions, I found this popular one https://github.com/marketplace/actions/jest-coverage-report but it uses an other format of jest output, which I try to use, but it seems impossible to merge our multiple tests in this format.
See here for more details about the formats: https://github.com/ArtiomTr/jest-coverage-report-action/issues/268

Using istambul merge we can only merge the format displayed on previous screenshot, we could have something maybe using a custom node script. The following one only merge partially the files and the final output is still in the wrong format:

```
const createReporter = require("istanbul-api").createReporter;
const istanbulCoverage = require("istanbul-lib-coverage");

const map = istanbulCoverage.createCoverageMap();
const reporter = createReporter();

const tests = ["documents-documents.spec.ts", "documents-documents-tab.spec.ts"];

tests.forEach(country => {
  const coverage = require(`../../coverage/coverage-report-${country}.json`);
  console.log(Object.keys(coverage.coverageMap));
  Object.keys(coverage.coverageMap).forEach(filename =>
    map.addFileCoverage(coverage.coverageMap[filename]),
  );
});

reporter.addAll(["json", "lcov", "text"]);
reporter.write(map);
```

**Comment by RomaricMourgues** [comment]
We can also use this one, it displays the right data but you need to unfold it or the by default data doesn't mean anything useful:

```
- name: Coverage
        uses: adRise/jest-cov-reporter@main
        with:
          branch-coverage-report-path: ./tdrive/coverage/merged/coverage-summary.json
          base-coverage-report-path: ./tdrive/coverage/merged/coverage-summary.json
          delta: 0.3
          fullCoverageDiff: true
          useSameComment: true
```

<img width="944" alt="Screenshot 2023-04-20 at 09 35 53" src="https://user-images.githubusercontent.com/14353924/233294220-adf250dd-c177-4a1a-aebd-958070940ce9.png">
